spring:
  application:
    name: eureka-server
  profiles:
    active: ${spring.profiles.active}
server:
  port: 1111
eureka:
  instance:
    instance-id: eureka-server
    prefer-ip-address: true
    appname: 注册中心
  client:
    # 一个注册中心时设为false,禁止注册自身;多个注册中心时设置为true
    register-with-eureka: false
    # 是否能够获取eureka注册信息
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file:
    name: eureka.log
    # 日志路径,需要修改
    path: C:\Users\dell\Desktop\log
    max-size: 100MB


info:
  name: ${spring.profiles.active}
  version: '@project.version@'
  encoding: '@project.build.sourceEncoding@'
  java:
    version: '@java.version@'